name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker stop react-container || true
            sudo docker rm react-container || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
            sudo docker run -d --name react-container -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
            sudo docker system prune -af

